coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 70%

ignore:
  - "web/dashboard/src/main.tsx"
  - "**/*.test.ts"
  - "**/*.test.py"
  - "**/node_modules/**"
  - "**/__pycache__/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default